const shell =require('shelljs');
shell.rm('-rf', 'dist');
shell.mkdir('-p','dist/google');
shell.mkdir('-p','dist/bin');
shell.cp('-R','protobuf-javascript/google/','dist/');
shell.cp('-R','protobuf-javascript/google-protobuf.js','dist/');
shell.cp('-R','protobuf-javascript/LICENSE*','dist/');
shell.cp('-R','protobuf-javascript/package.json','dist/');
shell.cp('-R','protobuf-javascript/README.md','dist/');
shell.cp('-R','protobuf-javascript/bazel-bin/generator/protoc-gen-js','dist/bin/');
